/*
 * southbound
 *
 * API generated from yang definitions: [aaa-encrypt-service-config,cli-topology,cli-translate-registry,cluster-singleton-service-impl,cluster-singleton-service-spi,config,fake,general-entity,ietf-inet-types,ietf-netconf,ietf-netconf-monitoring,ietf-netconf-monitoring-extension,ietf-netconf-notifications,ietf-yang-library,ietf-yang-types,journal,nc-notifications,netconf-keystore,netconf-node-inventory,netconf-node-topology,network-topology,network-topology,notifications,opendaylight-config-dom-datastore,opendaylight-entity-ownership-service,opendaylight-inmemory-datastore-provider,opendaylight-inventory,opendaylight-legacy-entity-ownership-service-provider,opendaylight-md-sal-common,opendaylight-md-sal-dom,opendaylight-operational-dom-datastore,rpc-context,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_southbound

type IetfNetconfMonitoringFormatIdentityref string

// List of ietf.netconf.monitoring.FormatIdentityref
const (
	IetfNetconfMonitoringFormatIdentityref_RNG IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:rng"
	IetfNetconfMonitoringFormatIdentityref_RNC IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:rnc"
	IetfNetconfMonitoringFormatIdentityref_SCHEMA_FORMAT IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:schema-format"
	IetfNetconfMonitoringFormatIdentityref_YIN IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:yin"
	IetfNetconfMonitoringFormatIdentityref_XSD IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:xsd"
	IetfNetconfMonitoringFormatIdentityref_YANG IetfNetconfMonitoringFormatIdentityref = "ietf-netconf-monitoring:yang"
)
