/*
 * southbound
 *
 * API generated from yang definitions: [aaa-encrypt-service-config,cli-topology,cli-translate-registry,cluster-singleton-service-impl,cluster-singleton-service-spi,config,fake,general-entity,ietf-inet-types,ietf-netconf,ietf-netconf-monitoring,ietf-netconf-monitoring-extension,ietf-netconf-notifications,ietf-yang-library,ietf-yang-types,journal,nc-notifications,netconf-keystore,netconf-node-inventory,netconf-node-topology,network-topology,network-topology,notifications,opendaylight-config-dom-datastore,opendaylight-entity-ownership-service,opendaylight-inmemory-datastore-provider,opendaylight-inventory,opendaylight-legacy-entity-ownership-service-provider,opendaylight-md-sal-common,opendaylight-md-sal-dom,opendaylight-operational-dom-datastore,rpc-context,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_southbound

// Optional.empty REF:Optional.empty
type NetconfNodeTopologyNetconfschemastorageYangLibrary struct {
	// Optional.empty REF:Optional.empty
	Password string `json:"password,omitempty"`
	// Optional[Yang library to be plugged as additional source provider into the shared schema repository] REF:Optional.empty
	YangLibraryUrl string `json:"yang-library-url,omitempty"`
	// Optional.empty REF:Optional.empty
	Username string `json:"username,omitempty"`
}
