/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

import (
	"bytes"
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"golang.org/x/oauth2"
)

var (
	jsonCheck = regexp.MustCompile("(?i:[application|text]/json)")
	xmlCheck  = regexp.MustCompile("(?i:[application|text]/xml)")
)

// APIClient manages communication with the unified API v4.2.0.frinx
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	cfg    *Configuration
	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// API Services

	FrinxAclExtensionApi *FrinxAclExtensionApiService

	FrinxBfdApi *FrinxBfdApiService

	FrinxBfdExtensionApi *FrinxBfdExtensionApiService

	FrinxBgpExtensionApi *FrinxBgpExtensionApiService

	FrinxCdpApi *FrinxCdpApiService

	FrinxCiscoIfExtensionApi *FrinxCiscoIfExtensionApiService

	FrinxCiscoMplsTeExtensionApi *FrinxCiscoMplsTeExtensionApiService

	FrinxCiscoOspfExtensionApi *FrinxCiscoOspfExtensionApiService

	FrinxDampingApi *FrinxDampingApiService

	FrinxEvpnApi *FrinxEvpnApiService

	FrinxHsrpApi *FrinxHsrpApiService

	FrinxJuniperPfInterfacesExtensionApi *FrinxJuniperPfInterfacesExtensionApiService

	FrinxL3ipvlanApi *FrinxL3ipvlanApiService

	FrinxLoggingApi *FrinxLoggingApiService

	FrinxNetflowApi *FrinxNetflowApiService

	FrinxOpenconfigAclApi *FrinxOpenconfigAclApiService

	FrinxOpenconfigBfdApi *FrinxOpenconfigBfdApiService

	FrinxOpenconfigBgpPolicyApi *FrinxOpenconfigBgpPolicyApiService

	FrinxOpenconfigIfAggregateApi *FrinxOpenconfigIfAggregateApiService

	FrinxOpenconfigIfEthernetApi *FrinxOpenconfigIfEthernetApiService

	FrinxOpenconfigIfIpApi *FrinxOpenconfigIfIpApiService

	FrinxOpenconfigIfIpExtApi *FrinxOpenconfigIfIpExtApiService

	FrinxOpenconfigInterfacesApi *FrinxOpenconfigInterfacesApiService

	FrinxOpenconfigIsisPolicyApi *FrinxOpenconfigIsisPolicyApiService

	FrinxOpenconfigLacpApi *FrinxOpenconfigLacpApiService

	FrinxOpenconfigLldpApi *FrinxOpenconfigLldpApiService

	FrinxOpenconfigNetworkInstanceApi *FrinxOpenconfigNetworkInstanceApiService

	FrinxOpenconfigNetworkInstancePolicyApi *FrinxOpenconfigNetworkInstancePolicyApiService

	FrinxOpenconfigOspfPolicyApi *FrinxOpenconfigOspfPolicyApiService

	FrinxOpenconfigPlatformApi *FrinxOpenconfigPlatformApiService

	FrinxOpenconfigPlatformLinecardApi *FrinxOpenconfigPlatformLinecardApiService

	FrinxOpenconfigPlatformPortApi *FrinxOpenconfigPlatformPortApiService

	FrinxOpenconfigPlatformTransceiverApi *FrinxOpenconfigPlatformTransceiverApiService

	FrinxOpenconfigProbesApi *FrinxOpenconfigProbesApiService

	FrinxOpenconfigQosApi *FrinxOpenconfigQosApiService

	FrinxOpenconfigRoutingPolicyApi *FrinxOpenconfigRoutingPolicyApiService

	FrinxOpenconfigVlanApi *FrinxOpenconfigVlanApiService

	FrinxSnmpApi *FrinxSnmpApiService
}

type service struct {
	client *APIClient
}

// NewAPIClient creates a new API client. Requires a userAgent string describing your application.
// optionally a custom http.Client to allow for advanced features such as caching.
func NewAPIClient(cfg *Configuration) *APIClient {
	if cfg.HTTPClient == nil {
		cfg.HTTPClient = http.DefaultClient
	}

	c := &APIClient{}
	c.cfg = cfg
	c.common.client = c

	// API Services
	c.FrinxAclExtensionApi = (*FrinxAclExtensionApiService)(&c.common)
	c.FrinxBfdApi = (*FrinxBfdApiService)(&c.common)
	c.FrinxBfdExtensionApi = (*FrinxBfdExtensionApiService)(&c.common)
	c.FrinxBgpExtensionApi = (*FrinxBgpExtensionApiService)(&c.common)
	c.FrinxCdpApi = (*FrinxCdpApiService)(&c.common)
	c.FrinxCiscoIfExtensionApi = (*FrinxCiscoIfExtensionApiService)(&c.common)
	c.FrinxCiscoMplsTeExtensionApi = (*FrinxCiscoMplsTeExtensionApiService)(&c.common)
	c.FrinxCiscoOspfExtensionApi = (*FrinxCiscoOspfExtensionApiService)(&c.common)
	c.FrinxDampingApi = (*FrinxDampingApiService)(&c.common)
	c.FrinxEvpnApi = (*FrinxEvpnApiService)(&c.common)
	c.FrinxHsrpApi = (*FrinxHsrpApiService)(&c.common)
	c.FrinxJuniperPfInterfacesExtensionApi = (*FrinxJuniperPfInterfacesExtensionApiService)(&c.common)
	c.FrinxL3ipvlanApi = (*FrinxL3ipvlanApiService)(&c.common)
	c.FrinxLoggingApi = (*FrinxLoggingApiService)(&c.common)
	c.FrinxNetflowApi = (*FrinxNetflowApiService)(&c.common)
	c.FrinxOpenconfigAclApi = (*FrinxOpenconfigAclApiService)(&c.common)
	c.FrinxOpenconfigBfdApi = (*FrinxOpenconfigBfdApiService)(&c.common)
	c.FrinxOpenconfigBgpPolicyApi = (*FrinxOpenconfigBgpPolicyApiService)(&c.common)
	c.FrinxOpenconfigIfAggregateApi = (*FrinxOpenconfigIfAggregateApiService)(&c.common)
	c.FrinxOpenconfigIfEthernetApi = (*FrinxOpenconfigIfEthernetApiService)(&c.common)
	c.FrinxOpenconfigIfIpApi = (*FrinxOpenconfigIfIpApiService)(&c.common)
	c.FrinxOpenconfigIfIpExtApi = (*FrinxOpenconfigIfIpExtApiService)(&c.common)
	c.FrinxOpenconfigInterfacesApi = (*FrinxOpenconfigInterfacesApiService)(&c.common)
	c.FrinxOpenconfigIsisPolicyApi = (*FrinxOpenconfigIsisPolicyApiService)(&c.common)
	c.FrinxOpenconfigLacpApi = (*FrinxOpenconfigLacpApiService)(&c.common)
	c.FrinxOpenconfigLldpApi = (*FrinxOpenconfigLldpApiService)(&c.common)
	c.FrinxOpenconfigNetworkInstanceApi = (*FrinxOpenconfigNetworkInstanceApiService)(&c.common)
	c.FrinxOpenconfigNetworkInstancePolicyApi = (*FrinxOpenconfigNetworkInstancePolicyApiService)(&c.common)
	c.FrinxOpenconfigOspfPolicyApi = (*FrinxOpenconfigOspfPolicyApiService)(&c.common)
	c.FrinxOpenconfigPlatformApi = (*FrinxOpenconfigPlatformApiService)(&c.common)
	c.FrinxOpenconfigPlatformLinecardApi = (*FrinxOpenconfigPlatformLinecardApiService)(&c.common)
	c.FrinxOpenconfigPlatformPortApi = (*FrinxOpenconfigPlatformPortApiService)(&c.common)
	c.FrinxOpenconfigPlatformTransceiverApi = (*FrinxOpenconfigPlatformTransceiverApiService)(&c.common)
	c.FrinxOpenconfigProbesApi = (*FrinxOpenconfigProbesApiService)(&c.common)
	c.FrinxOpenconfigQosApi = (*FrinxOpenconfigQosApiService)(&c.common)
	c.FrinxOpenconfigRoutingPolicyApi = (*FrinxOpenconfigRoutingPolicyApiService)(&c.common)
	c.FrinxOpenconfigVlanApi = (*FrinxOpenconfigVlanApiService)(&c.common)
	c.FrinxSnmpApi = (*FrinxSnmpApiService)(&c.common)

	return c
}

func atoi(in string) (int, error) {
	return strconv.Atoi(in)
}

// selectHeaderContentType select a content type from the available list.
func selectHeaderContentType(contentTypes []string) string {
	if len(contentTypes) == 0 {
		return ""
	}
	if contains(contentTypes, "application/json") {
		return "application/json"
	}
	return contentTypes[0] // use the first content type specified in 'consumes'
}

// selectHeaderAccept join all accept types and return
func selectHeaderAccept(accepts []string) string {
	if len(accepts) == 0 {
		return ""
	}

	if contains(accepts, "application/json") {
		return "application/json"
	}

	return strings.Join(accepts, ",")
}

// contains is a case insenstive match, finding needle in a haystack
func contains(haystack []string, needle string) bool {
	for _, a := range haystack {
		if strings.ToLower(a) == strings.ToLower(needle) {
			return true
		}
	}
	return false
}

// Verify optional parameters are of the correct type.
func typeCheckParameter(obj interface{}, expected string, name string) error {
	// Make sure there is an object.
	if obj == nil {
		return nil
	}

	// Check the type is as expected.
	if reflect.TypeOf(obj).String() != expected {
		return fmt.Errorf("Expected %s to be of type %s but received %s.", name, expected, reflect.TypeOf(obj).String())
	}
	return nil
}

// parameterToString convert interface{} parameters to string, using a delimiter if format is provided.
func parameterToString(obj interface{}, collectionFormat string) string {
	var delimiter string

	switch collectionFormat {
	case "pipes":
		delimiter = "|"
	case "ssv":
		delimiter = " "
	case "tsv":
		delimiter = "\t"
	case "csv":
		delimiter = ","
	}

	if reflect.TypeOf(obj).Kind() == reflect.Slice {
		return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
	}

	return fmt.Sprintf("%v", obj)
}

// callAPI do the request.
func (c *APIClient) callAPI(request *http.Request) (*http.Response, error) {
	return c.cfg.HTTPClient.Do(request)
}

// Change base path to allow switching to mocks
func (c *APIClient) ChangeBasePath(path string) {
	c.cfg.BasePath = path
}

// prepareRequest build the request
func (c *APIClient) prepareRequest(
	ctx context.Context,
	path string, method string,
	postBody interface{},
	headerParams map[string]string,
	queryParams url.Values,
	formParams url.Values,
	fileName string,
	fileBytes []byte) (localVarRequest *http.Request, err error) {

	var body *bytes.Buffer

	// Detect postBody type and post.
	if postBody != nil {
		contentType := headerParams["Content-Type"]
		if contentType == "" {
			contentType = detectContentType(postBody)
			headerParams["Content-Type"] = contentType
		}

		body, err = setBody(postBody, contentType)
		if err != nil {
			return nil, err
		}
	}

	// add form parameters and file if available.
	if len(formParams) > 0 || (len(fileBytes) > 0 && fileName != "") {
		if body != nil {
			return nil, errors.New("Cannot specify postBody and multipart form at the same time.")
		}
		body = &bytes.Buffer{}
		w := multipart.NewWriter(body)

		for k, v := range formParams {
			for _, iv := range v {
				if strings.HasPrefix(k, "@") { // file
					err = addFile(w, k[1:], iv)
					if err != nil {
						return nil, err
					}
				} else { // form value
					w.WriteField(k, iv)
				}
			}
		}
		if len(fileBytes) > 0 && fileName != "" {
			w.Boundary()
			//_, fileNm := filepath.Split(fileName)
			part, err := w.CreateFormFile("file", filepath.Base(fileName))
			if err != nil {
				return nil, err
			}
			_, err = part.Write(fileBytes)
			if err != nil {
				return nil, err
			}
			// Set the Boundary in the Content-Type
			headerParams["Content-Type"] = w.FormDataContentType()
		}

		// Set Content-Length
		headerParams["Content-Length"] = fmt.Sprintf("%d", body.Len())
		w.Close()
	}

	// Setup path and query parameters
	url, err := url.Parse(path)
	if err != nil {
		return nil, err
	}

	// Adding Query Param
	query := url.Query()
	for k, v := range queryParams {
		for _, iv := range v {
			query.Add(k, iv)
		}
	}

	// Encode the parameters.
	url.RawQuery = query.Encode()

	// Generate a new request
	if body != nil {
		localVarRequest, err = http.NewRequest(method, url.String(), body)
	} else {
		localVarRequest, err = http.NewRequest(method, url.String(), nil)
	}
	if err != nil {
		return nil, err
	}

	// add header parameters, if any
	if len(headerParams) > 0 {
		headers := http.Header{}
		for h, v := range headerParams {
			headers.Set(h, v)
		}
		localVarRequest.Header = headers
	}

	// Override request host, if applicable
	if c.cfg.Host != "" {
		localVarRequest.Host = c.cfg.Host
	}

	// Add the user agent to the request.
	localVarRequest.Header.Add("User-Agent", c.cfg.UserAgent)

	if ctx != nil {
		// add context to the request
		localVarRequest = localVarRequest.WithContext(ctx)

		// Walk through any authentication.

		// OAuth2 authentication
		if tok, ok := ctx.Value(ContextOAuth2).(oauth2.TokenSource); ok {
			// We were able to grab an oauth2 token from the context
			var latestToken *oauth2.Token
			if latestToken, err = tok.Token(); err != nil {
				return nil, err
			}

			latestToken.SetAuthHeader(localVarRequest)
		}

		// Basic HTTP Authentication
		if auth, ok := ctx.Value(ContextBasicAuth).(BasicAuth); ok {
			localVarRequest.SetBasicAuth(auth.UserName, auth.Password)
		}

		// AccessToken Authentication
		if auth, ok := ctx.Value(ContextAccessToken).(string); ok {
			localVarRequest.Header.Add("Authorization", "Bearer "+auth)
		}
	}

	for header, value := range c.cfg.DefaultHeader {
		localVarRequest.Header.Add(header, value)
	}

	return localVarRequest, nil
}

func (c *APIClient) decode(v interface{}, b []byte, contentType string) (err error) {
		if strings.Contains(contentType, "application/xml") {
			if err = xml.Unmarshal(b, v); err != nil {
				return err
			}
			return nil
		} else if strings.Contains(contentType, "application/json") {
			if err = json.Unmarshal(b, v); err != nil {
				return err
			}
			return nil
		}
	return errors.New("undefined response type")
}

// Add a file to the multipart request
func addFile(w *multipart.Writer, fieldName, path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()

	part, err := w.CreateFormFile(fieldName, filepath.Base(path))
	if err != nil {
		return err
	}
	_, err = io.Copy(part, file)

	return err
}

// Prevent trying to import "fmt"
func reportError(format string, a ...interface{}) error {
	return fmt.Errorf(format, a...)
}

// Set request body from an interface{}
func setBody(body interface{}, contentType string) (bodyBuf *bytes.Buffer, err error) {
	if bodyBuf == nil {
		bodyBuf = &bytes.Buffer{}
	}

	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if b, ok := body.([]byte); ok {
		_, err = bodyBuf.Write(b)
	} else if s, ok := body.(string); ok {
		_, err = bodyBuf.WriteString(s)
	} else if s, ok := body.(*string); ok {
		_, err = bodyBuf.WriteString(*s)
	} else if jsonCheck.MatchString(contentType) {
		err = json.NewEncoder(bodyBuf).Encode(body)
	} else if xmlCheck.MatchString(contentType) {
		xml.NewEncoder(bodyBuf).Encode(body)
	}

	if err != nil {
		return nil, err
	}

	if bodyBuf.Len() == 0 {
		err = fmt.Errorf("Invalid body type %s\n", contentType)
		return nil, err
	}
	return bodyBuf, nil
}

// detectContentType method is used to figure out `Request.Body` content type for request header
func detectContentType(body interface{}) string {
	contentType := "text/plain; charset=utf-8"
	kind := reflect.TypeOf(body).Kind()

	switch kind {
	case reflect.Struct, reflect.Map, reflect.Ptr:
		contentType = "application/json; charset=utf-8"
	case reflect.String:
		contentType = "text/plain; charset=utf-8"
	default:
		if b, ok := body.([]byte); ok {
			contentType = http.DetectContentType(b)
		} else if kind == reflect.Slice {
			contentType = "application/json; charset=utf-8"
		}
	}

	return contentType
}

// Ripped from https://github.com/gregjones/httpcache/blob/master/httpcache.go
type cacheControl map[string]string

func parseCacheControl(headers http.Header) cacheControl {
	cc := cacheControl{}
	ccHeader := headers.Get("Cache-Control")
	for _, part := range strings.Split(ccHeader, ",") {
		part = strings.Trim(part, " ")
		if part == "" {
			continue
		}
		if strings.ContainsRune(part, '=') {
			keyval := strings.Split(part, "=")
			cc[strings.Trim(keyval[0], " ")] = strings.Trim(keyval[1], ",")
		} else {
			cc[part] = ""
		}
	}
	return cc
}

// CacheExpires helper function to determine remaining time before repeating a request.
func CacheExpires(r *http.Response) time.Time {
	// Figure out when the cache expires.
	var expires time.Time
	now, err := time.Parse(time.RFC1123, r.Header.Get("date"))
	if err != nil {
		return time.Now()
	}
	respCacheControl := parseCacheControl(r.Header)

	if maxAge, ok := respCacheControl["max-age"]; ok {
		lifetime, err := time.ParseDuration(maxAge + "s")
		if err != nil {
			expires = now
		}
		expires = now.Add(lifetime)
	} else {
		expiresHeader := r.Header.Get("Expires")
		if expiresHeader != "" {
			expires, err = time.Parse(time.RFC1123, expiresHeader)
			if err != nil {
				expires = now
			}
		}
	}
	return expires
}

func strlen(s string) int {
	return utf8.RuneCountInString(s)
}

// GenericSwaggerError Provides access to the body, error and model on returned errors.
type GenericSwaggerError struct {
	body  []byte
	error string
	model interface{}
}

// Error returns non-empty string if there was an error.
func (e GenericSwaggerError) Error() string {
	return e.error
}

// Body returns the raw bytes of the response
func (e GenericSwaggerError) Body() []byte {
	return e.body
}

// Model returns the unpacked model of the error
func (e GenericSwaggerError) Model() interface{} {
	return e.model
}