/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[This container defines global ISIS configuration and state information.] REF:Optional.empty
type FrinxOpenconfigIsisIsistopIsisGlobal struct {
	// Optional[This container defines address-family specific configuration and state information.] REF:Optional.empty
	AfiSafi *FrinxOpenconfigIsisIsisglobalbaseAfiSafi `json:"afi-safi,omitempty"`
	// Optional[This container defines IGP shortcuts configuration and state information.] REF:Optional.empty
	IgpShortcuts *FrinxOpenconfigIsisIsisglobalbaseIgpShortcuts `json:"igp-shortcuts,omitempty"`
	// Optional[This container defines ISIS timers.] REF:Optional.empty
	Timers *FrinxOpenconfigIsisIsisglobalbaseTimers `json:"timers,omitempty"`
	// Optional[This container defines ISIS LSP Operational Bits.] REF:Optional.empty
	LspBit *FrinxOpenconfigIsisIsisglobalbaseLspBit `json:"lsp-bit,omitempty"`
	// Optional[Configuration and operational state relating to MPLS-related features in IS-IS] REF:Optional.empty
	Mpls *FrinxOpenconfigIsisIsisglobalbaseMpls `json:"mpls,omitempty"`
	// Optional[This container defines ISIS Graceful Restart.] REF:Optional.empty
	GracefulRestart *FrinxOpenconfigIsisIsisglobalbaseGracefulRestart `json:"graceful-restart,omitempty"`
	// Optional[This container defines ISIS Reference Bandwidth.] REF:Optional.empty
	ReferenceBandwidth *FrinxOpenconfigIsisIsisglobalbaseReferenceBandwidth `json:"reference-bandwidth,omitempty"`
	// Optional[This container defines ISIS transport.] REF:Optional.empty
	Transport *FrinxOpenconfigIsisIsisglobalbaseTransport `json:"transport,omitempty"`
	// Optional[Policies to propagate prefixes between IS-IS levels.] REF:Optional.empty
	InterLevelPropagationPolicies *FrinxOpenconfigIsisInterlevelpropagationpoliciesstructuralInterLevelPropagationPolicies `json:"inter-level-propagation-policies,omitempty"`
	// Optional[This container defines ISIS Non-Stop Routing.] REF:Optional.empty
	Nsr *FrinxOpenconfigIsisIsisglobalbaseNsr `json:"nsr,omitempty"`
	// Optional[This container defines ISIS global configuration router.] REF:Optional.empty
	Config *FrinxOpenconfigIsisIsisglobalbaseConfig `json:"config,omitempty"`
}
