/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[List of ACL entries comprising an ACL set] REF:Optional.empty
type FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclEntry struct {
	// Optional.empty REF:Optional.empty
	FrinxAclExtensionicmp *FrinxAclExtensionAclicmptypeIcmp `json:"frinx-acl-extension:icmp,omitempty"`
	// Optional[Top level container for IPv4 match field data] REF:Optional.empty
	Ipv4 *FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclentryIpv4 `json:"ipv4,omitempty"`
	// Optional[Top-level container for IPv6 match field data] REF:Optional.empty
	Ipv6 *FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclentryIpv6 `json:"ipv6,omitempty"`
	// Optional[Ethernet header fields] REF:Optional.empty
	L2 *FrinxOpenconfigPacketMatchEthernetheadertopL2 `json:"l2,omitempty"`
	// Optional[references the list key] REF:Optional.empty
	SequenceId int64 `json:"sequence-id,omitempty"`
	// Optional[Input interface container] REF:Optional.empty
	InputInterface *FrinxOpenconfigAclInputinterfacetopInputInterface `json:"input-interface,omitempty"`
	// Optional[Transport fields container] REF:Optional.empty
	Transport *FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclentryTransport `json:"transport,omitempty"`
	// Optional[Enclosing container for list of ACL actions associated with an entry] REF:Optional.empty
	Actions *FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclentryActions `json:"actions,omitempty"`
	// Optional[Access list entries config] REF:Optional.empty
	Config *FrinxOpenconfigAclAclAclsetsAclsetAclentriesAclentryConfig `json:"config,omitempty"`
}
