/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[This container defines ISIS global configuration router.] REF:Optional.empty
type FrinxOpenconfigIsisIsisglobalbaseConfig struct {
	// Optional[ISIS max-paths count.] REF:Optional.empty
	MaxEcmpPaths int32 `json:"max-ecmp-paths,omitempty"`
	// Optional[ISIS Instance.] REF:Optional.empty
	Instance string `json:"instance,omitempty"`
	// Optional[When set to true, reject all ISIS protocol PDUs that either have a mismatch in authentication-type or authentication-key.] REF:Optional.empty
	AuthenticationCheck bool `json:"authentication-check,omitempty"`
	// Optional[Maximum areas supported.] REF:Optional.empty
	MaximumAreaAddresses int32 `json:"maximum-area-addresses,omitempty"`
	// Optional[ISIS Instance Identifier TLV. When set to trues, the IID-TLV identifies the unique instance as well as the topology/topologies to which the PDU applies.] REF:Optional[RFC6822: IS-IS Multi-Instance. TLV 7]
	IidTlv bool `json:"iid-tlv,omitempty"`
	// Optional[ISIS level capability(level-1, level-2,vlevel-1-2).] REF:Optional.empty
	LevelCapability *FrinxOpenconfigIsisTypesLevelType `json:"level-capability,omitempty"`
	// Optional[When set to true, IS will always flood the LSP that triggered an SPF before the router actually runs the SPF computation.] REF:Optional.empty
	FastFlooding bool `json:"fast-flooding,omitempty"`
	// Optional[ISIS purge TLV. When set to true, a TLV is added to purges to record the system ID  of the IS generating the purge.] REF:Optional[RFC6232: Purge Originator Identification TLV for IS-IS. TLV 13.]
	PoiTlv bool `json:"poi-tlv,omitempty"`
	// Optional[ISIS network entity title (NET). The first 8 bits are usually 49 (private AFI), next 16 bits represent area, next 48 bits represent system id and final 8 bits are set to 0.] REF:Optional[International Organization for Standardization, Information technology - Open Systems Interconnection-Network service Definition - ISO/ IEC 8348:2002.]
	Net []string `json:"net,omitempty"`
}
