/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[Configuration data for 2 rate, 3 color policers.] REF:Optional.empty
type FrinxOpenconfigQosQosscheduler2r3ctopTworatethreecolorConfig struct {
	// Optional[Committed burst size for the dual-rate token bucket policer.  This value represents the depth of the token bucket.] REF:Optional.empty
	Bc int64 `json:"bc,omitempty"`
	// Optional[Committed information rate for the dual-rate token bucket policer. This value represents the rate at which tokens are added to the primary bucket. It is expressed as a percentage of the total bandwidth available within the context the scheduler is instantiated.] REF:Optional.empty
	CirPct int32 `json:"cir-pct,omitempty"`
	// Optional[Excess burst size for the dual-rate token bucket policer. This value represents the depth of the secondary bucket.] REF:Optional.empty
	Be int64 `json:"be,omitempty"`
	// Optional[Committed information rate for the dual-rate token bucket policer. This value represents the rate at which tokens are added to the primary bucket. It is expressed as a percentage of the remaining bandwidth within the context the scheduler is instantiated.] REF:Optional.empty
	CirPctRemaining int32 `json:"cir-pct-remaining,omitempty"`
	// Optional[Peak information rate for the dual-rate token bucket policer.  This value represents the rate at which tokens are added to the secondary bucket.] REF:Optional.empty
	Pir int32 `json:"pir,omitempty"`
	// Optional[Peak information rate for the dual-rate token bucket policer. This value represents the rate at which tokens are added to the secondary bucket. It is expressed as a percentage of the remaining bandwidth within the context the scheduler is instantiated.] REF:Optional.empty
	PirPctRemaining int32 `json:"pir-pct-remaining,omitempty"`
	// Optional[Committed information rate for the dual-rate token bucket policer.  This value represents the rate at which tokens are added to the primary bucket.] REF:Optional.empty
	Cir int32 `json:"cir,omitempty"`
	// Optional[Peak information rate for the dual-rate token bucket policer. This value represents the rate at which tokens are added to the secondary bucket. The value is expressed as a percentage of the total bandwidth available in the context in which the scheduler is instantiated.] REF:Optional.empty
	PirPct int32 `json:"pir-pct,omitempty"`
}
