/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[The list of subinterfaces (logical interfaces) associated with a physical interface] REF:Optional.empty
type FrinxOpenconfigInterfacesInterfacesInterfaceSubinterfacesSubinterface struct {
	// Optional[Parameters for the IPv4 address family.] REF:Optional.empty
	FrinxOpenconfigIfIpipv4 *FrinxOpenconfigIfIpIpv4topIpv4 `json:"frinx-openconfig-if-ip:ipv4,omitempty"`
	// Optional[Enclosing container for VLAN interface-specific data on subinterfaces] REF:Optional.empty
	FrinxOpenconfigVlanvlan *FrinxOpenconfigVlanVlanlogicaltopVlan `json:"frinx-openconfig-vlan:vlan,omitempty"`
	// Optional[Parameters for the IPv6 address family.] REF:Optional.empty
	FrinxOpenconfigIfIpipv6 *FrinxOpenconfigIfIpIpv6topIpv6 `json:"frinx-openconfig-if-ip:ipv6,omitempty"`
	// Optional[Enclosing container for statistics interface-specific data.] REF:Optional.empty
	FrinxCiscoIfExtensionstatistics *FrinxCiscoIfExtensionStatisticstopStatistics `json:"frinx-cisco-if-extension:statistics,omitempty"`
	// Optional[The index number of the subinterface -- used to address the logical interface] REF:Optional.empty
	Index int64 `json:"index,omitempty"`
	// Optional[Top-level container for hold-time settings to enable dampening advertisements of interface transitions.] REF:Optional.empty
	FrinxCiscoIfExtensionholdTime *FrinxOpenconfigInterfacesInterfacephysholdtimetopHoldTime `json:"frinx-cisco-if-extension:hold-time,omitempty"`
	// Optional[Configurable items at the subinterface level] REF:Optional.empty
	Config *FrinxOpenconfigInterfacesInterfacesInterfaceSubinterfacesSubinterfaceConfig `json:"config,omitempty"`
}
