/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[Configuration parameters related to paths] REF:Optional.empty
type FrinxOpenconfigMplsP2pprimarypathstopP2pprimarypathP2pprimarypathConfig struct {
	// Optional[Address of the external path computation server] REF:Optional.empty
	PathComputationServer string `json:"path-computation-server,omitempty"`
	// Optional[Determine the tie-breaking method to choose between equally desirable paths during CSFP computation] REF:Optional.empty
	CspfTiebreaker *FrinxOpenconfigMplsCspfTieBreaking `json:"cspf-tiebreaker,omitempty"`
	// Optional[Flag to enable CSPF for locally computed LSPs] REF:Optional.empty
	UseCspf bool `json:"use-cspf,omitempty"`
	// Optional[Specifies a preference for this path. The lower the number higher the preference] REF:Optional.empty
	Preference int32 `json:"preference,omitempty"`
	// Optional[Path name] REF:Optional.empty
	Name string `json:"name,omitempty"`
	// Optional[sets the time between attempts to establish the LSP] REF:Optional.empty
	RetryTimer int32 `json:"retry-timer,omitempty"`
	// Optional[The method used for computing the path, either locally computed, queried from a server or not computed at all (explicitly configured).] REF:Optional.empty
	PathComputationMethod *FrinxOpenconfigMplsPathComputationMethodIdentityref `json:"path-computation-method,omitempty"`
	// Optional[RSVP-TE preemption priority during LSP setup, lower is higher priority; default 7 indicates that LSP will not preempt established LSPs during setup] REF:Optional[RFC 3209 - RSVP-TE: Extensions to RSVP for LSP Tunnels]
	SetupPriority int32 `json:"setup-priority,omitempty"`
	// Optional[preemption priority once the LSP is established, lower is higher priority; default 0 indicates other LSPs will not preempt the LSPs once established] REF:Optional[RFC 3209 - RSVP-TE: Extensions to RSVP for LSP Tunnels]
	HoldPriority int32 `json:"hold-priority,omitempty"`
	// Optional[reference to a defined path] REF:Optional.empty
	ExplicitPathName string `json:"explicit-path-name,omitempty"`
}
