/*
 * unified
 *
 * API generated from yang definitions: [fake,frinx-acl-extension,frinx-bfd,frinx-bfd-extension,frinx-bgp-extension,frinx-cdp,frinx-cisco-if-extension,frinx-cisco-mpls-te-extension,frinx-cisco-ospf-extension,frinx-cisco-pf-interfaces-extension,frinx-damping,frinx-dasan-vlan-extension,frinx-event-types,frinx-evpn,frinx-evpn-types,frinx-hsrp,frinx-if-aggregate-extension,frinx-isis-extension,frinx-juniper-if-aggregate-extension,frinx-juniper-if-extension,frinx-juniper-pf-interfaces-extension,frinx-juniper-probes-extension,frinx-l3ipvlan,frinx-lacp-lag-member,frinx-logging,frinx-mpls-ldp-extension,frinx-mpls-rsvp-extension,frinx-netflow,frinx-openconfig-acl,frinx-openconfig-bfd,frinx-openconfig-bgp,frinx-openconfig-bgp-policy,frinx-openconfig-bgp-types,frinx-openconfig-extensions,frinx-openconfig-if-aggregate,frinx-openconfig-if-ethernet,frinx-openconfig-if-ip,frinx-openconfig-if-ip-ext,frinx-openconfig-inet-types,frinx-openconfig-interfaces,frinx-openconfig-isis,frinx-openconfig-isis-lsdb-types,frinx-openconfig-isis-policy,frinx-openconfig-isis-types,frinx-openconfig-lacp,frinx-openconfig-lldp,frinx-openconfig-lldp-types,frinx-openconfig-local-routing,frinx-openconfig-mpls,frinx-openconfig-mpls-ldp,frinx-openconfig-mpls-rsvp,frinx-openconfig-mpls-types,frinx-openconfig-network-instance,frinx-openconfig-network-instance-l3,frinx-openconfig-network-instance-policy,frinx-openconfig-network-instance-types,frinx-openconfig-ospf-policy,frinx-openconfig-ospf-types,frinx-openconfig-ospfv2,frinx-openconfig-packet-match,frinx-openconfig-packet-match-types,frinx-openconfig-platform,frinx-openconfig-platform-linecard,frinx-openconfig-platform-port,frinx-openconfig-platform-transceiver,frinx-openconfig-platform-types,frinx-openconfig-policy-forwarding,frinx-openconfig-policy-types,frinx-openconfig-probes,frinx-openconfig-probes-types,frinx-openconfig-qos,frinx-openconfig-qos-types,frinx-openconfig-rib-bgp,frinx-openconfig-rib-bgp-ext,frinx-openconfig-rib-bgp-types,frinx-openconfig-routing-policy,frinx-openconfig-transport-types,frinx-openconfig-types,frinx-openconfig-vlan,frinx-openconfig-vlan-types,frinx-openconfig-yang-types,frinx-ospf-extension,frinx-qos-extension,frinx-snmp,frinx-uniconfig-topology,iana-if-type,ietf-inet-types,ietf-interfaces,ietf-yang-types,network-topology,network-topology,unified-topology,yang-ext]
 *
 * API version: 4.2.0.frinx
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger_unified

// Optional[Global configuration parameters for OSPFv2] REF:Optional.empty
type FrinxOpenconfigOspfv2Ospfv2globalstructuralGlobalConfig struct {
	// Optional[When this leaf is set to true, OSPFv2 will route traffic to a remote system via any LSP to the system that is marked as shortcut eligible.] REF:Optional.empty
	IgpShortcuts bool `json:"igp-shortcuts,omitempty"`
	// Optional[When this leaf is set to true, a log message will be generated when the state of an OSPFv2 neighbour changes.] REF:Optional.empty
	LogAdjacencyChanges bool `json:"log-adjacency-changes,omitempty"`
	// Optional[When this leaf is set to true, do not advertise prefixes into OSPFv2 that correspond to transit interfaces, as per the behaviour discussed in RFC6860.] REF:Optional[RFC6860 - Hiding Transit-Only Networks in OSPF]
	HideTransitOnlyNetworks bool `json:"hide-transit-only-networks,omitempty"`
	// Optional[Specify how costs for the summary routes should be specified as per the behaviour in the original OSPF specification RFC1583, or alternatively whether the revised behaviour described in RFC2328 should be utilised] REF:Optional.empty
	SummaryRouteCostMode *FrinxOpenconfigOspfv2SummaryRouteCostModeEnumeration `json:"summary-route-cost-mode,omitempty"`
	// Optional[A 32-bit number represented as a dotted quad assigned to each router running the OSPFv2 protocol. This number should be unique within the autonomous system] REF:Optional[rfc2828]
	RouterId string `json:"router-id,omitempty"`
}
